import type { Project, Service, Sector, Testimonial, JournalPost } from "@shared/schema";

export const projects: Project[] = [
  {
    id: "7",
    slug: "tugo-artisan-baking",
    title: "Tugo Artisan Baking",
    client: "Tugo",
    sector: "Food & Hospitality",
    serviceType: "Brand & Corporate Films",
    description: "Capturing the craft and passion behind artisan baking at Tugo.",
    challenge: "",
    approach: "",
    outcome: "",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1036052545",
    thumbnailUrl: "https://i.vimeocdn.com/video/1957683725-cfb468cc435781c51e19f63c5020c5665f86fb5f383a192718a217c062640921-d_640x360",
    featured: true,
    order: 1,
  },
  {
    id: "8",
    slug: "tugo-sourdough-craft",
    title: "Tugo Sourdough Craft",
    client: "Tugo",
    sector: "Food & Hospitality",
    serviceType: "Brand & Corporate Films",
    description: "Showcasing the artistry and technique of sourdough production.",
    challenge: "",
    approach: "",
    outcome: "",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1044952338",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968447495-f4a670f39e695910f20fb8e35a77f0994758a018bf49c035431cd8f806394cde-d_640x360",
    featured: true,
    order: 2,
  },
  {
    id: "1",
    slug: "horizon-logistics-recruitment",
    title: "Attracting Talent in a Competitive Market",
    client: "Horizon Logistics",
    sector: "Recruitment & Employer Branding",
    serviceType: "Recruitment & Employer Brand",
    description: "A documentary-style recruitment film showcasing authentic employee stories and company culture.",
    challenge: "Horizon Logistics struggled to attract quality candidates in a competitive market where every logistics firm promised the same benefits.",
    approach: "We spent time with real employees, capturing their genuine experiences through documentary interviews. No scripts, no rehearsals—just authentic stories that revealed the company's true culture.",
    outcome: "The film resulted in a 47% increase in quality applications and significantly reduced time-to-hire for key positions.",
    testimonial: "The documentary approach captured something we couldn't articulate ourselves. Candidates now arrive already understanding our culture.",
    testimonialAuthor: "Sarah Mitchell",
    testimonialRole: "Head of Talent Acquisition",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=450&fit=crop",
    featured: false,
    order: 3,
  },
  {
    id: "2",
    slug: "sterling-wealth-brand-film",
    title: "Building Trust Through Transparency",
    client: "Sterling Wealth Partners",
    sector: "Financial Services",
    serviceType: "Brand & Corporate Films",
    description: "A brand film that humanised a wealth management firm in an industry often perceived as impersonal.",
    challenge: "Sterling needed to differentiate from competitors while meeting FCA Consumer Duty requirements for clear communication.",
    approach: "We crafted a narrative around their client relationships, featuring real advisors and clients discussing complex topics in accessible language.",
    outcome: "The film achieved 2.3x higher engagement than industry benchmarks and helped onboard 34% more new clients.",
    testimonial: "They understood financial services in a way most video companies don't. The result was both compliant and compelling.",
    testimonialAuthor: "James Thornton",
    testimonialRole: "Managing Director",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=450&fit=crop",
    featured: true,
    order: 2,
  },
  {
    id: "3",
    slug: "precision-engineering-case-study",
    title: "Manufacturing Excellence in Focus",
    client: "Precision Engineering Ltd",
    sector: "Manufacturing & Health Safety",
    serviceType: "Documentary-Style Case Studies",
    description: "A case study film demonstrating manufacturing precision and workplace safety culture.",
    challenge: "Precision Engineering needed to showcase their capabilities to potential clients while highlighting their exemplary safety record.",
    approach: "We embedded ourselves in their facility, capturing the craftsmanship and attention to detail that defined their work. Safety wasn't just mentioned—it was woven into every frame.",
    outcome: "The film became a key sales tool, directly contributing to three major contract wins worth over £2 million.",
    testimonial: "The team understood manufacturing. They captured what makes us different in a way that resonated with our clients.",
    testimonialAuthor: "David Chen",
    testimonialRole: "Operations Director",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=450&fit=crop",
    featured: true,
    order: 3,
  },
  {
    id: "4",
    slug: "silverstone-racing-documentary",
    title: "Behind the Racing Team",
    client: "Apex Racing",
    sector: "Motorsport",
    serviceType: "Event & Motorsport Films",
    description: "A behind-the-scenes documentary capturing the intensity and human stories of a British racing team.",
    challenge: "Apex Racing wanted content that went beyond race highlights to show the dedication and teamwork behind their success.",
    approach: "We followed the team through a complete race weekend, from early morning preparations to podium celebrations, capturing the human drama alongside the action.",
    outcome: "The documentary series increased sponsor engagement by 65% and attracted three new team sponsors.",
    testimonial: "They captured the passion and dedication that drives our team. This wasn't just race footage—it was storytelling.",
    testimonialAuthor: "Emma Richards",
    testimonialRole: "Team Principal",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1558981001-5864b3250a69?w=800&h=450&fit=crop",
    featured: true,
    order: 4,
  },
  {
    id: "5",
    slug: "biotech-innovation-showcase",
    title: "Making Science Accessible",
    client: "NovaBio Research",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "A film translating complex biotechnology innovations into compelling visual storytelling.",
    challenge: "NovaBio needed to communicate breakthrough research to investors and partners without losing scientific credibility.",
    approach: "We worked closely with their scientists to understand the research, then crafted visual metaphors and narratives that made complex concepts accessible without oversimplifying.",
    outcome: "The film helped secure £5 million in additional funding and attracted two major pharmaceutical partnerships.",
    testimonial: "They made our science understandable without dumbing it down. Our investors and partners finally got it.",
    testimonialAuthor: "Dr. Rachel Foster",
    testimonialRole: "Chief Scientific Officer",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=450&fit=crop",
    featured: false,
    order: 5,
  },
  {
    id: "6",
    slug: "oxford-tech-employer-brand",
    title: "Tech Talent Attraction",
    client: "Oxford Innovation Hub",
    sector: "Scientific & Tech",
    serviceType: "Recruitment & Employer Brand",
    description: "A recruitment campaign showcasing Oxford's unique tech ecosystem and career opportunities.",
    challenge: "Oxford Innovation Hub needed to compete with London for top tech talent while highlighting their unique advantages.",
    approach: "We documented the experiences of developers, researchers, and entrepreneurs who chose Oxford over the capital, creating authentic testimonials about work-life balance and innovation culture.",
    outcome: "The campaign generated 89% more qualified applications and reduced reliance on expensive recruitment agencies.",
    testimonial: "The authentic stories convinced candidates to take a closer look at Oxford. We're now competing effectively with London firms.",
    testimonialAuthor: "Michael Okonkwo",
    testimonialRole: "Head of People",
    vimeoId: "824804225",
    thumbnailUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=450&fit=crop",
    featured: false,
    order: 6,
  },
];

export const services: Service[] = [
  {
    id: "1",
    slug: "brand-corporate-films",
    title: "Brand & Corporate Films",
    shortDescription: "Films that capture your essence, not just your messaging.",
    description: "Documentary-style brand films that reveal who you truly are. We go beyond surface-level messaging to capture the authentic character of your organisation.",
    icon: "Film",
    whoIsFor: "Marketing directors and brand managers who know their company is more than their competitors but struggle to communicate that difference authentically.",
    problemSolved: "Generic corporate videos feel interchangeable—polished but forgettable. They tell people what you do, but never show who you are.",
    whyFilmmakerLed: "Documentary techniques reveal authentic moments and genuine emotion. We create narrative structure that engages viewers, not just informs them.",
    whatMakesDifferent: "We spend time understanding your culture before we ever press record. Our films feature real people, real stories, and real moments that resonate.",
    deliverables: "Hero brand film (2-4 minutes), social cut-downs, behind-the-scenes content, strategy documentation",
    priceFrom: "£4,500",
    order: 1,
  },
  {
    id: "2",
    slug: "recruitment-employer-brand",
    title: "Recruitment & Employer Brand",
    shortDescription: "Attract talent with stories that ring true.",
    description: "Documentary-approach recruitment videos that showcase your genuine culture and attract candidates who'll thrive in your environment.",
    icon: "Users",
    whoIsFor: "HR directors and talent acquisition leaders competing for talent in tight labour markets where every company claims to be a 'great place to work'.",
    problemSolved: "Candidates see through scripted testimonials. Staged videos with employees reading from prompts feel fake—and talent knows it.",
    whyFilmmakerLed: "Documentary interview techniques draw out authentic stories. We create conditions where real employees share genuine experiences.",
    whatMakesDifferent: "We interview without scripts, finding the moments of genuine enthusiasm and honest reflection that convince candidates your culture is real.",
    deliverables: "Recruitment film (2-3 minutes), individual role spotlights, day-in-the-life content, LinkedIn-optimised cuts",
    priceFrom: "£3,500",
    order: 2,
  },
  {
    id: "3",
    slug: "documentary-case-studies",
    title: "Documentary-Style Case Studies",
    shortDescription: "Client success stories told with depth and credibility.",
    description: "Case study films that demonstrate your impact through authentic client stories, building trust and credibility with prospects.",
    icon: "BookOpen",
    whoIsFor: "B2B businesses with complex offerings where trust and proven results matter more than flashy promises.",
    problemSolved: "Written case studies lack emotional impact. Generic video testimonials feel rehearsed and fail to convey the full story of transformation.",
    whyFilmmakerLed: "We approach case studies as mini-documentaries, capturing the journey from challenge to solution to outcome with narrative structure.",
    whatMakesDifferent: "We interview both your team and your clients, weaving perspectives into a complete story that demonstrates value authentically.",
    deliverables: "Case study film (3-5 minutes), quote clips, prospect-specific edits, sales enablement content",
    priceFrom: "£3,000",
    order: 3,
  },
  {
    id: "4",
    slug: "presenter-coaching",
    title: "Presenter & Interviewee Coaching",
    shortDescription: "Prepare your team to shine on camera.",
    description: "Documentary filmmaker techniques applied to helping executives and team members communicate authentically and confidently on camera.",
    icon: "Mic",
    whoIsFor: "Leaders and team members who need to appear on camera but feel uncomfortable, stiff, or inauthentic when filmed.",
    problemSolved: "Most people hate being on camera. They become robotic, forget key messages, or look uncomfortable—undermining the content you're creating.",
    whyFilmmakerLed: "Documentary filmmakers specialise in making real people comfortable and authentic. We know how to draw out genuine presence.",
    whatMakesDifferent: "We use documentary interview techniques to help people find their natural voice, building confidence through practice and feedback.",
    deliverables: "One-on-one coaching sessions, group workshops, on-set support, preparation frameworks",
    priceFrom: "£800",
    order: 4,
  },
  {
    id: "5",
    slug: "event-motorsport-films",
    title: "Event & Motorsport Films",
    shortDescription: "Capturing the energy and drama of live moments.",
    description: "High-energy event coverage and motorsport documentation that captures the atmosphere, emotion, and key moments of your live events.",
    icon: "Zap",
    whoIsFor: "Event organisers, motorsport teams, and brands who want to extend the impact of their live events through compelling video content.",
    problemSolved: "Standard event coverage captures what happened, but misses the atmosphere and emotion. You need content that makes viewers wish they'd been there.",
    whyFilmmakerLed: "Documentary filmmakers capture authentic moments and human stories within the action. We find the narrative in the chaos.",
    whatMakesDifferent: "We go beyond coverage to storytelling—finding the characters, tensions, and resolutions that make events memorable.",
    deliverables: "Event highlight film, real-time social content, interview packages, promotional trailers",
    priceFrom: "£2,500",
    order: 5,
  },
];

export const sectors: Sector[] = [
  {
    id: "6",
    slug: "food-hospitality",
    title: "Food & Hospitality",
    shortDescription: "Capturing the craft, passion, and stories behind food and hospitality brands.",
    description: "Food and hospitality businesses thrive on authenticity and craft. Documentary-style video captures the passion, skill, and human stories that make your brand memorable.",
    industryKnowledge: "In an era of artisan food movements and farm-to-table dining, customers want to know the story behind what they eat. They're seeking genuine connections with the people who make their food.",
    whyDocumentaryWorks: "Documentary approach reveals the craft and dedication behind every dish. We capture the early mornings, the precise techniques, and the pride that goes into artisan production.",
    experience: "We've worked with bakeries, restaurants, and food producers to create content that showcases their authentic story and connects with food-loving audiences.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    order: 1,
  },
  {
    id: "1",
    slug: "recruitment-employer-branding",
    title: "Recruitment & Employer Branding",
    shortDescription: "Authentic employer brand content that attracts talent who'll thrive.",
    description: "In today's competitive talent market, authentic employer branding is essential. We help organisations cut through the noise with genuine employee stories.",
    industryKnowledge: "The recruitment landscape has fundamentally changed. Candidates research employers thoroughly before applying, and they can spot inauthenticity instantly. Generic 'great place to work' messaging no longer convinces anyone.",
    whyDocumentaryWorks: "Candidates see through scripted testimonials. Documentary approach draws out genuine employee stories that resonate because they're real. We create conditions for authentic sharing, not rehearsed performances.",
    experience: "We've produced 50+ recruitment videos for organisations across sectors, from logistics firms to tech startups. Our clients report an average 40% increase in quality applications.",
    testimonial: "The documentary approach captured something we couldn't articulate ourselves. Candidates now arrive already understanding our culture.",
    testimonialAuthor: "Sarah Mitchell",
    testimonialRole: "Head of Talent Acquisition, Horizon Logistics",
    order: 2,
  },
  {
    id: "2",
    slug: "financial-services",
    title: "Financial Services",
    shortDescription: "Compliant, compelling video for regulated industries.",
    description: "Financial services face unique challenges: regulatory requirements, complex products, and the need to build trust in an industry often viewed with scepticism.",
    industryKnowledge: "FCA Consumer Duty requirements now mandate clear communication. Generic videos don't meet compliance standards, and overly technical content fails to engage clients.",
    whyDocumentaryWorks: "Documentary approach humanises financial services. We capture real client relationships and genuine expertise, making complex topics accessible while maintaining credibility.",
    experience: "We've worked with wealth managers, insurance providers, and fintech firms. Our content achieves 2x higher engagement than industry benchmarks while meeting compliance requirements.",
    testimonial: "They understood financial services in a way most video companies don't. The result was both compliant and compelling.",
    testimonialAuthor: "James Thornton",
    testimonialRole: "Managing Director, Sterling Wealth Partners",
    order: 2,
  },
  {
    id: "3",
    slug: "manufacturing-health-safety",
    title: "Manufacturing & Health Safety",
    shortDescription: "Showcasing craftsmanship and safety excellence.",
    description: "Manufacturing businesses need to demonstrate quality, precision, and safety. Documentary approach captures the expertise and dedication that define manufacturing excellence.",
    industryKnowledge: "Manufacturing faces perception challenges: automation concerns, skills gaps, and the need to attract younger workers. Video must showcase the craft and innovation that define modern manufacturing.",
    whyDocumentaryWorks: "Documentary filmmaking captures the pride and precision of manufacturing work. We show the human expertise behind every process, building appreciation for craftsmanship.",
    experience: "We've documented manufacturing processes from precision engineering to food production. Our films become sales tools that directly contribute to contract wins.",
    testimonial: "The team understood manufacturing. They captured what makes us different in a way that resonated with our clients.",
    testimonialAuthor: "David Chen",
    testimonialRole: "Operations Director, Precision Engineering Ltd",
    order: 3,
  },
  {
    id: "4",
    slug: "motorsport",
    title: "Motorsport",
    shortDescription: "The drama, dedication, and human stories behind racing.",
    description: "Motorsport is drama, dedication, and split-second decisions. Based near Silverstone in Motorsport Valley, we understand the culture and stories that make racing compelling.",
    industryKnowledge: "Motorsport content needs to go beyond race highlights. Sponsors want to see their values reflected; fans want access to the human stories behind the helmets.",
    whyDocumentaryWorks: "Documentary approach captures the intensity and human drama that makes motorsport compelling. We find the stories within the action, the characters within the competition.",
    experience: "From British GT to grassroots racing, we've documented teams across motorsport. Our content increases sponsor engagement and attracts new partnerships.",
    testimonial: "They captured the passion and dedication that drives our team. This wasn't just race footage—it was storytelling.",
    testimonialAuthor: "Emma Richards",
    testimonialRole: "Team Principal, Apex Racing",
    order: 4,
  },
  {
    id: "5",
    slug: "scientific-tech",
    title: "Scientific & Tech",
    shortDescription: "Making complex innovation accessible and compelling.",
    description: "Scientific and technology organisations face the challenge of communicating complex ideas to diverse audiences—investors, partners, customers, and the public.",
    industryKnowledge: "Tech and science content often falls into two traps: oversimplifying to the point of inaccuracy, or remaining so technical that non-experts switch off. Neither builds trust.",
    whyDocumentaryWorks: "Documentary approach brings out the passion behind innovation. We help scientists and technologists share their work in ways that inspire without compromising accuracy.",
    experience: "We've worked with biotech firms, research institutions, and tech startups. Our content helps secure funding, attract talent, and build public understanding.",
    testimonial: "They made our science understandable without dumbing it down. Our investors and partners finally got it.",
    testimonialAuthor: "Dr. Rachel Foster",
    testimonialRole: "Chief Scientific Officer, NovaBio Research",
    order: 5,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote: "The documentary approach captured something we couldn't articulate ourselves. Candidates now arrive already understanding our culture.",
    author: "Sarah Mitchell",
    role: "Head of Talent Acquisition",
    company: "Horizon Logistics",
    sector: "Recruitment",
    featured: true,
    order: 1,
  },
  {
    id: "2",
    quote: "They understood financial services in a way most video companies don't. The result was both compliant and compelling.",
    author: "James Thornton",
    role: "Managing Director",
    company: "Sterling Wealth Partners",
    sector: "Financial Services",
    featured: true,
    order: 2,
  },
  {
    id: "3",
    quote: "The team understood manufacturing. They captured what makes us different in a way that resonated with our clients.",
    author: "David Chen",
    role: "Operations Director",
    company: "Precision Engineering Ltd",
    sector: "Manufacturing",
    featured: false,
    order: 3,
  },
];

export const journalPosts: JournalPost[] = [
  {
    id: "1",
    slug: "why-documentary-approach-works-for-business",
    title: "Why Documentary Approach Works for Business Video",
    excerpt: "Generic corporate video fails because it treats businesses like products to be advertised. Documentary approach treats them as stories to be told.",
    content: "Full article content here...",
    category: "Documentary Technique",
    readTime: 5,
    published: true,
    createdAt: new Date("2024-12-15"),
  },
  {
    id: "2",
    slug: "interview-techniques-for-authentic-testimonials",
    title: "Interview Techniques for Authentic Testimonials",
    excerpt: "The difference between a rehearsed testimonial and a genuine one isn't script versus no script—it's how you create the conditions for authenticity.",
    content: "Full article content here...",
    category: "Behind the Scenes",
    readTime: 7,
    published: true,
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "3",
    slug: "recruitment-video-mistakes-to-avoid",
    title: "5 Recruitment Video Mistakes That Drive Candidates Away",
    excerpt: "Most recruitment videos fail because they tell candidates what the company wants them to hear, not what they need to know.",
    content: "Full article content here...",
    category: "Industry Insights",
    readTime: 6,
    published: true,
    createdAt: new Date("2024-11-20"),
  },
];

export const clientLogos = [
  { name: "Tugo", initials: "TG" },
  { name: "Horizon Logistics", initials: "HL" },
  { name: "Sterling Wealth", initials: "SW" },
  { name: "Precision Engineering", initials: "PE" },
  { name: "Apex Racing", initials: "AR" },
  { name: "NovaBio Research", initials: "NB" },
  { name: "Oxford Innovation", initials: "OI" },
  { name: "Midlands Manufacturing", initials: "MM" },
];

export const pricingTiers = [
  {
    name: "Spark",
    price: "£2,000",
    description: "For businesses beginning their video journey",
    features: [
      "Half-day shoot (2-4 hours)",
      "One filmmaker",
      "One final video (60-90 seconds)",
      "2 social cut-downs",
      "Basic motion graphics",
      "Music licensing",
      "2 revision rounds",
      "2-3 week delivery",
    ],
    highlighted: false,
  },
  {
    name: "Ignite",
    price: "£4,500",
    description: "Most popular — for growing brands",
    features: [
      "Full-day shoot (8 hours)",
      "2-person crew",
      "One hero video (2-3 minutes)",
      "3-4 social cut-downs",
      "Standard motion graphics",
      "Professional voiceover",
      "Music licensing",
      "Strategy session pre-shoot",
      "3 revision rounds",
      "3-4 week delivery",
    ],
    highlighted: true,
  },
  {
    name: "Blaze",
    price: "£8,000",
    description: "For ambitious brands with bigger stories",
    features: [
      "Multi-day shoot (2+ days)",
      "Full crew",
      "Multiple locations",
      "Flagship video + content suite",
      "Advanced motion graphics",
      "Professional voiceover + sound design",
      "Content strategy workshop",
      "Full RAW footage delivery",
      "Priority turnaround",
    ],
    highlighted: false,
  },
];
