import type { Project, Service, Sector, Testimonial, JournalPost } from "./types";

export const projects: Project[] = [
  {
    id: "fb-013",
    slug: "bibby-recruitment-campaign",
    title: "Bibby Recruitment Campaign Film",
    client: "Bibby Financial Services",
    sector: "Financial Services",
    serviceType: "Brand film",
    description: "Real, raw, and human national hiring campaign",
    challenge: "Bibby needed a recruitment approach that felt genuinely different in a sector known for corporate formality.",
    approach: "Designed to be inviting and honest, blending professional footage with mobile clips and outtakes. Built around laughter, personality, and genuine reasons employees love working at Bibby.",
    outcome: "Flagship recruitment asset delivering culture-led storytelling across Oxfordshire and Manchester.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "946594314",
    thumbnailUrl: "https://i.vimeocdn.com/video/1852754909-203ae33b118f2514cf59c35dae845d8bfbfc82717baeded0c4faf116c44c05b0-d_640",
    featured: true,
    order: 1,
  },
  {
    id: "fb-017",
    slug: "hero-era-peking-to-paris",
    title: "Peking to Paris Build-Up Film",
    client: "HERO ERA",
    sector: "Motorsport",
    serviceType: "Brand film",
    description: "Broadcast-grade edit from mixed footage sources",
    challenge: "Combining in-house footage with additional filming into a cohesive story for international audiences.",
    approach: "Combined in-house videographer footage with additional Flashbuzz filming, edited into a cohesive build-up story. An alternative edit was submitted as a BBC programme concept.",
    outcome: "Broadcast-ready editorial proof with international credibility - the programme was later picked up by Italian television.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "874094700",
    thumbnailUrl: "https://i.vimeocdn.com/video/1737911998-3de4b1fcd3c9f9d20fb6ebfe7baf4c69e49003f9e2e47fc588ced2abff4c5f83-d_640",
    featured: false,
    order: 2,
  },
  {
    id: "fb-016",
    slug: "hero-era-prodrive-mustang-build",
    title: "HERO ERA x Prodrive Mustang Build",
    client: "HERO ERA x Prodrive",
    sector: "Motorsport",
    serviceType: "Documentary-Style Case Studies",
    description: "Documentary partnership film in motorsport engineering",
    challenge: "Capturing the full journey of a restoration project from discovery to handover.",
    approach: "Tracks an abandoned American Mustang being found, rebuilt, and fine-tuned at Prodrive's facility, then collected by its billionaire owner. Narrative-led documentary showcasing heritage, engineering, and ambition.",
    outcome: "Premium brand storytelling and partnership credibility film.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "874094766",
    thumbnailUrl: "https://i.vimeocdn.com/video/1739040196-3f4af77ca06e693ed7cfc2493fa825ffe4d4109dc39c9d2313a42062232fcceb-d_640",
    featured: false,
    order: 3,
  },
  {
    id: "fb-014",
    slug: "john-lewis-interactive-induction",
    title: "John Lewis Interactive Induction Film",
    client: "John Lewis",
    sector: "Recruitment & Employer Branding",
    serviceType: "Brand & Corporate Films",
    description: "Video designed to integrate into live training",
    challenge: "John Lewis wanted a fundamentally different induction experience that felt immersive.",
    approach: "The video is shot and paced to feel like the viewer is in a real induction, with trainers pausing the film for live activities then resuming, creating a seamless blended training environment.",
    outcome: "Modernised onboarding experience that was highly praised by the client.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "946546831",
    thumbnailUrl: "https://i.vimeocdn.com/video/1852688495-f0985bcbb3315965eced12c3d36344ddb7b9ceb233c18a635ef4bf0a29233dfe-d_640",
    featured: false,
    order: 4,
  },
  {
    id: "fb-010",
    slug: "smyths-toys-flagship-recruitment",
    title: "Smyths Toys Flagship Recruitment Advert",
    client: "Smyths Toys",
    sector: "Recruitment & Employer Branding",
    serviceType: "Recruitment & Employer Brand",
    description: "The main social hiring campaign for the year",
    challenge: "Creating an authentic recruitment presence that stands out in retail.",
    approach: "Built as Smyths' key recruitment advert for the year, designed to feel authentic and approachable while showcasing the team, culture, and environment candidates can expect.",
    outcome: "National recruitment asset with strong employer branding.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1005891597",
    thumbnailUrl: "https://i.vimeocdn.com/video/1922528926-ad60c698db88b75a29639f5d0d77a61057140f349a054cdda1bc8f7a39e06e01-d_640",
    featured: false,
    order: 5,
  },
  {
    id: "fb-002",
    slug: "smyths-toys-recruitment-social",
    title: "Smyths Toys Recruitment Social Campaign",
    client: "Smyths Toys",
    sector: "Recruitment & Employer Branding",
    serviceType: "Recruitment & Employer Brand",
    description: "Personality-led hiring content for TikTok and Instagram",
    challenge: "Positioning Smyths as a modern employer on social platforms.",
    approach: "Vertical video campaign built for TikTok and Instagram to position Smyths as a modern employer that celebrates individuality. Focused on staff character and culture to help future colleagues connect with the people behind the brand.",
    outcome: "Improved employer appeal on social media and recruitment marketing assets.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045006123",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968515478-3b013efd840757b960bd1ae11ea02d6b1f7f8a512043f7d3f80cb4ee3ddaa9f7-d_640",
    featured: false,
    order: 6,
  },
  {
    id: "fb-009",
    slug: "white-stuff-warehouse-induction",
    title: "White Stuff Warehouse Induction Film",
    client: "White Stuff",
    sector: "Recruitment & Employer Branding",
    serviceType: "Brand & Corporate Films",
    description: "Culture plus first-day and H&S messaging",
    challenge: "Delivering consistent onboarding at scale while communicating culture.",
    approach: "Collaboration with Quest Employment for White Stuff onboarding. Communicates why working there is different while delivering first-day and safety messaging to ensure confidence and consistency at scale.",
    outcome: "Improved onboarding clarity and consistent first-day experience.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1005891269",
    thumbnailUrl: "https://i.vimeocdn.com/video/1922531927-bc2599c70814d237c4b38a29f8f8810a400fd1fb781c045c253afc6de41c4033-d_640",
    featured: false,
    order: 7,
  },
  {
    id: "fb-007",
    slug: "tugo-foods-pizza-concepts",
    title: "Tugo Foods Pizza Concepts Showcase",
    client: "Tugo Foods",
    sector: "Food & Hospitality",
    serviceType: "Purpose-led video",
    description: "High-energy split-screen food marketing",
    challenge: "Demonstrating product ease and support in an engaging format.",
    approach: "Split-screen, top-down sequence to show how easy two pizza products are to produce and how much support Tugo provides to partners adopting their concepts. Part of a long-term partnership producing high-volume food content.",
    outcome: "Partner enablement content and consistent brand marketing output.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1044658459",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968093018-294fa11772cfd5c50d3dfa2b454db00e19942e19786c7cf96b084766bce82cfd-d_640",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813444/vegetable_sweet_n_sour__2_1080p_xipyof.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813444/vegetable_sweet_n_sour__2_1080p_xipyof.jpg",
    theBrief: "Elevate perception and differentiate brand category — position Tugo as a rapid, creative culinary supplier for food service, not fast food.",
    approachBullets: [
      "Appetite-led close-ups",
      "Fast-paced edits",
      "Stylised modern tone",
    ],
    tags: ["Food marketing", "Product video", "Food service", "Brand positioning"],
    year: 2024,
    featured: false,
    order: 8,
  },
  {
    id: "fb-008",
    slug: "tugo-foods-pizza-box-oven",
    title: "Tugo Foods Pizza Box Oven Advert",
    client: "Tugo Foods",
    sector: "Food & Hospitality",
    serviceType: "Purpose-led video",
    description: "Visual hook that screams speed and efficiency",
    challenge: "Communicating product speed in a memorable, visual way.",
    approach: "Chef builds the pizza, closes the lid, then heat and smoke reveal the pizza cooked instantly when reopened. A fast, memorable way to communicate how efficient Tugo pizzas are in food service environments.",
    outcome: "Clear speed message and high-impact product advert.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1036052545",
    thumbnailUrl: "https://i.vimeocdn.com/video/1957683725-cfb468cc435781c51e19f63c5020c5665f86fb5f383a192718a217c062640921-d_640",
    featured: false,
    order: 9,
  },
  {
    id: "fb-015",
    slug: "tugo-foods-behind-the-scenes",
    title: "Tugo Foods Behind the Scenes",
    client: "Tugo Foods",
    sector: "Food & Hospitality",
    serviceType: "Brand & Corporate Films",
    description: "From chef prep to polished cinematic shot",
    challenge: "Building trust through transparency in the creative process.",
    approach: "Shows chefs finishing dishes at the development table, then reveals the final polished shot filmed using an electronic slider rig mounted upside down, gliding across food on a white table. Highlights craft and collaboration.",
    outcome: "Trust-building craft content and marketing transparency asset.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "922909719",
    thumbnailUrl: "https://i.vimeocdn.com/video/1814199499-2b553d8a3f1b5ed7d1d8d4263c3a91270ef7095511fc057abf4153a4e2b5ba20-d_640",
    featured: false,
    order: 10,
  },
  {
    id: "fb-001",
    slug: "voneus-community-fun-run",
    title: "Voneus Community Fun Run",
    client: "Voneus",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Community-first brand storytelling",
    challenge: "Humanising a tech brand through visible community engagement.",
    approach: "Voneus sponsors a fun run for Shipston Home Nursing to raise funds and strengthen local presence. Flashbuzz captured their involvement, the people behind the brand, and the atmosphere of the day to humanise the business and raise brand profile through authentic community storytelling.",
    outcome: "Brand visibility through community engagement and authentic event-led content.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045006678",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968525064-c01bdbb1fc13ca0a6286d8f90ea0580fec5377dfa1f70d2836fdcd567461301d-d_640",
    featured: false,
    order: 11,
  },
  {
    id: "fb-012",
    slug: "flutter-shutter-pitch-film",
    title: "Flutter Shutter Pitch Film",
    client: "Flutter Shutter",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Sustainability innovation for social housing",
    challenge: "Supporting procurement pitches for an innovative cleantech startup.",
    approach: "All-female startup creating shutters to reduce heat loss in social housing. With existing contracts secured, the film supported future large procurement pitches by clearly explaining the problem, solution, credibility, and impact.",
    outcome: "Procurement support asset and clear innovation story.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "946594818",
    thumbnailUrl: "https://i.vimeocdn.com/video/1852839574-0583132491853ce50f90db664efcbb349d170942d42df9869f8cc2b60ddacf38-d_640",
    featured: false,
    order: 12,
  },
  {
    id: "fb-018",
    slug: "catherine-house-hospice-awareness",
    title: "Catherine House Hospice Awareness Film",
    client: "Catherine House Hospice",
    sector: "Charity & Healthcare",
    serviceType: "Brand film",
    description: "Sensitive, emotionally intelligent charity storytelling",
    challenge: "Telling a sensitive story about end-of-life care with dignity.",
    approach: "Film created to raise awareness of Catherine House Hospice and the need for continual community support to sustain end-of-life care services. Required high sensitivity and respectful storytelling throughout production.",
    outcome: "Awareness asset and fundraising support messaging.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "849885872",
    thumbnailUrl: "https://i.vimeocdn.com/video/1713895958-66ce5480baf7a32d94908aef282d956810e208d061bd2371813ad28f9c9ad844-d_640",
    featured: false,
    order: 13,
  },
  {
    id: "fb-005",
    slug: "shipston-home-nursing-fundraising",
    title: "Shipston Home Nursing Fundraising Film",
    client: "Shipston Home Nursing",
    sector: "Charity & Awareness",
    serviceType: "Brand & Corporate Films",
    description: "Purpose-led storytelling with recognised talent",
    challenge: "Driving awareness and fundraising support for a local charity.",
    approach: "Fundraising and awareness film for Shipston Home Nursing, designed to communicate mission and drive support. Featured Anton Lesser to add recognition and gravitas while keeping the focus on the charity's work and community impact.",
    outcome: "Awareness uplift and fundraising support asset.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045007307",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968513313-0d88f2768027ae43eb31a89f02a9b1e0b838b5ce5c13acaf3dfa8e81db4347a3-d_640",
    featured: false,
    order: 14,
  },
  {
    id: "fb-011",
    slug: "beauty-above-launch-event",
    title: "Beauty Above Launch Event Film",
    client: "Beauty Above",
    sector: "Hospitality & Lifestyle",
    serviceType: "Brand & Corporate Films",
    description: "Founder-led launch content built for lead gen",
    challenge: "Capturing a startup launch while building lead generation assets.",
    approach: "Startup salon launch in Oxfordshire. Flashbuzz captured the event and gave the owners a confident platform to communicate values and ethos, then used it as awareness and lead generation content across social.",
    outcome: "Awareness content and lead generation video asset.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "991606026",
    thumbnailUrl: "https://i.vimeocdn.com/video/1907462720-b882887a9a3e97f0f2aa38fb20c5fe905f97b5907546f1bfa72e393dbb7d8ea1-d_640",
    featured: false,
    order: 15,
  },
  {
    id: "fb-003",
    slug: "beardmail-oxford-street-activation",
    title: "Beardmail Oxford Street Activation",
    client: "Beardmail",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Guerrilla launch content with humour and energy",
    challenge: "Generating leads and attention for a startup launch.",
    approach: "Beardmail launched a playful street campaign using postbox costumes and public interviews to introduce their beard grooming packs. Flashbuzz captured real reactions and shaped the content into an upbeat social edit that generated attention and leads.",
    outcome: "Lead generation content and social campaign assets.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045007856",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968514357-9ac787d4cd613c4c39aa64a93847600aea0147835e7b146cd6a2c95c00024507-d_640",
    featured: false,
    order: 16,
  },
  {
    id: "fb-006",
    slug: "fine-fettle-dream-sequence",
    title: "Fine Fettle Dream Sequence Social Ad",
    client: "Fine Fettle",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Quirky concept-led grooming advert",
    challenge: "Positioning a product as identity and lifestyle, not just product.",
    approach: "Damien escapes the rat race into the woods, smashing his laptop and embracing his inner wild bearded self. Flashbuzz created a playful dream-sequence narrative to position Fine Fettle as identity and lifestyle, not just product.",
    outcome: "Memorable brand advert and social campaign asset.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045007567",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968508560-b8b6b027c4572fcb43ff01725d66816e6864432d132635a2fdda7eb19fca38e1-d_640",
    featured: false,
    order: 17,
  },
  {
    id: "fb-004",
    slug: "bearded-viking-axe-masters-promo",
    title: "Bearded Viking Axe Masters Promo",
    client: "Bearded Viking Axe Masters",
    sector: "Food & Hospitality",
    serviceType: "Brand & Corporate Films",
    description: "Experience-led film that drives bookings",
    challenge: "Showcasing a unique venue experience to drive corporate and consumer bookings.",
    approach: "Charismatic owner Damo wanted a film that showcased facilities and the Viking-themed experience. Flashbuzz captured atmosphere, humour, and energy to drive corporate events interest and consumer bookings as an evergreen marketing asset.",
    outcome: "Ongoing bookings interest and corporate events enquiries.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "1045007069",
    thumbnailUrl: "https://i.vimeocdn.com/video/1968513884-0a2f7ef4bd94e5cc900cf3f0f100f83d96a57f886b4a6dee46d5186ab3d63899-d_640",
    featured: false,
    order: 18,
  },
  {
    id: "fb-019",
    slug: "spring-chicken-tipping-kettle",
    title: "Tipping Kettle Product Demo",
    client: "Spring Chicken",
    sector: "Scientific & Tech",
    serviceType: "Purpose-led video",
    description: "Clear, safety-first e-commerce video for mobility support",
    challenge: "Demonstrating accessibility product benefits with clarity.",
    approach: "One-shot demonstration designed for clarity and confidence at purchase. Shows how a tipping kettle makes pouring easier and safer for users with reduced mobility.",
    outcome: "Improved product understanding and conversion support.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "255253550",
    thumbnailUrl: "https://i.vimeocdn.com/video/682615287-ee0d23a72d2253f69d2341c339a927b4c3d784f39948de3aa0bcd43104ed3b03-d_640",
    featured: false,
    order: 19,
  },
  {
    id: "fb-020",
    slug: "spring-chicken-non-tip-cup",
    title: "Non-Tip Cup Product Demo",
    client: "Spring Chicken",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Spill-resistant daily living support",
    challenge: "Communicating product benefit instantly for accessibility products.",
    approach: "Clean, functional demo showing stability and spill prevention for customers with mobility issues. Built to reassure and communicate benefit instantly.",
    outcome: "Reduced uncertainty at purchase and clear functional messaging.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: "255238480",
    thumbnailUrl: "https://i.vimeocdn.com/video/682597129-94dbc3636032240ddab0dfb22f49d4c1328393ca0218743347889f30c7308d39-d_640",
    featured: false,
    order: 20,
  },
  {
    id: "fb-021",
    slug: "doorfit-team-portraits",
    title: "Doorfit Team Portraits",
    client: "Doorfit",
    sector: "Manufacturing & Trade",
    serviceType: "Photography — Team Portraits",
    description: "Team portraits for a UK door hardware specialist, shot on location with a portable studio setup. Half-day engagement.",
    challenge: "Refreshing team imagery for a long-established door hardware specialist with a consistent, professional look.",
    approach: "On-site portrait shoot delivering clean, brand-appropriate headshots suitable for web, sales materials, and trade press.",
    outcome: "Modern stills library aligned to the company's positioning, ready for marketing and recruitment use.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_640,h_400,c_fill,q_auto,f_auto/Doorfit_48_k6ls8g",
    featured: false,
    order: 21,
  },
  {
    id: "fb-023",
    slug: "voneus-brand-stills",
    title: "Voneus Brand Stills",
    client: "Voneus",
    sector: "Scientific & Tech",
    serviceType: "Photography — Brand Stills",
    description: "Brand photography that humanises a UK rural broadband provider",
    challenge: "Building a primary visual library for a tech business in a category usually represented by stock photography of fibre cables.",
    approach: "Full-day brand stills shoot capturing the operations team, customer environments, and community events — the real texture of the business rather than generic sector imagery.",
    outcome: "Twenty-two image set that became Voneus's primary visual library for the year, used across web, social, decks, and PR.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_640,h_400,c_fill,q_auto,f_auto/voneus_01",
    featured: true,
    order: 22,
  },
  {
    id: "fb-022",
    slug: "oxford-beard-festival",
    title: "Oxford Beard Festival",
    client: "Oxford Beard Festival",
    sector: "Hospitality & Lifestyle",
    serviceType: "Event & Motorsport Films",
    description: "Quirky, character-led cultural event film",
    challenge: "Capture the culture, humour, and competitive spirit of the festival in a watchable, cinematic way.",
    approach: "Character-led coverage focusing on contestants and champions, capturing atmosphere, detail, and energy with an edit that celebrates the unique culture.",
    outcome: "Additional sizzle reel produced and pitched to Channel 4 for a one-off documentary exploring beard festivals and their culture.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813167/social_edit.mp4_1080p_dqnacl.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813167/social_edit.mp4_1080p_dqnacl.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813167/social_edit.mp4_1080p_dqnacl.jpg",
    theBrief: "Capture the culture, humour, and competitive spirit of the festival in a watchable, cinematic way.",
    approachBullets: [
      "Character-led coverage focusing on contestants and champions",
      "Capturing atmosphere, detail, and energy",
      "Energy-driven edit that celebrates the unique culture",
    ],
    tags: ["Event", "Documentary", "Culture", "Sizzle reel", "Broadcast development"],
    year: 2023,
    hero: true,
    featured: false,
    order: 22,
  },
  {
    id: "fb-023",
    slug: "redwings-horse-sanctuary",
    title: "Redwings Horse Sanctuary",
    client: "Redwings Horse Sanctuary",
    sector: "Charity & Awareness",
    serviceType: "Documentary-Style Case Studies",
    description: "Awareness film for Strangles Awareness Week",
    challenge: "Raise awareness with an honest, sensitive campaign film for Strangles Awareness Week, visiting real horse stables and speaking with owners about managing this devastating disease.",
    approach: "Real contributors in real environments, interview-led storytelling, and a restrained, respectful edit.",
    outcome: "Strong audience reception and part of a wider series of awareness films for the campaign.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813425/redwings_1080p_tibalh.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813425/redwings_1080p_tibalh.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813425/redwings_1080p_tibalh.jpg",
    theBrief: "Raise awareness with an honest, sensitive campaign film.",
    approachBullets: [
      "Real contributors in real environments",
      "Interview-led storytelling",
      "Restrained, respectful edit",
    ],
    tags: ["Charity", "Awareness", "Documentary", "Animals"],
    year: 2023,
    hero: true,
    featured: false,
    order: 23,
  },
  {
    id: "fb-024",
    slug: "warm-front",
    title: "Warm Front Home Insulation Film",
    client: "Warm Front",
    sector: "Public Sector & Property",
    serviceType: "Documentary-Style Case Studies",
    description: "Project showcase film for home insulation works",
    challenge: "Serve two audiences: homeowners (reassurance) and housing associations (credibility), supporting new regional contracts.",
    approach: "Filmed real properties showing process and outcomes, with a calm, informative tone and a polished, procurement-friendly edit.",
    outcome: "A trust-building comms asset supporting transparency and new partnership conversations.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813448/senior_warmfront_manager_discussion__alex_hearn_.mp4_1080p_u6ge2j.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813448/senior_warmfront_manager_discussion__alex_hearn_.mp4_1080p_u6ge2j.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813448/senior_warmfront_manager_discussion__alex_hearn_.mp4_1080p_u6ge2j.jpg",
    theBrief: "Serve two audiences: homeowners (reassurance) and housing associations (credibility).",
    approachBullets: [
      "Real properties showing process and outcomes",
      "Calm, informative tone",
      "Polished, procurement-friendly edit",
    ],
    tags: ["Housing", "Public sector", "Infrastructure", "Sustainability"],
    year: 2024,
    hero: true,
    featured: false,
    order: 24,
  },
  {
    id: "fb-025",
    slug: "glucowear-medical-device-launch",
    title: "GlucoWear US Product Launch Film",
    client: "GlucoWear",
    sector: "Scientific & Tech",
    serviceType: "Brand & Corporate Films",
    description: "Product launch film for a medical technology startup",
    challenge: "Communicate innovation and credibility for a high-stakes US launch event audience for a medical technology startup with significant EU funding.",
    approach: "Premium tone throughout, prioritising clarity over complexity with event-ready pacing.",
    outcome: "Strong visual anchor for launch presentations and stakeholder conversations.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813470/glucowear_3__1_1080p_uemmq5.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813470/glucowear_3__1_1080p_uemmq5.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813470/glucowear_3__1_1080p_uemmq5.jpg",
    theBrief: "Communicate innovation and credibility for a high-stakes international audience.",
    approachBullets: [
      "Premium tone throughout",
      "Clarity over complexity",
      "Event-ready pacing",
    ],
    tags: ["Product launch", "MedTech", "Startup", "International"],
    year: 2024,
    featured: false,
    order: 25,
  },
  {
    id: "fb-026",
    slug: "industrial-recruitment-montage",
    title: "Industrial Recruitment & Health and Safety Montage",
    client: "Industrial Recruitment Montage",
    sector: "Recruitment & Employer Branding",
    serviceType: "Recruitment & Employer Brand",
    description: "Showreel of recruitment and H&S work in regulated environments",
    challenge: "Demonstrate breadth of work and competence in regulated logistics, warehouse, and industrial environments.",
    approach: "Real workplaces and authentic environments with an authoritative tone, prioritising clarity and pace without gimmicks.",
    outcome: "A strong proof asset for large employers and procurement teams.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813461/flashbuzz_warehouse_induction_showreel_1080p_hsz8hw.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813461/flashbuzz_warehouse_induction_showreel_1080p_hsz8hw.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813461/flashbuzz_warehouse_induction_showreel_1080p_hsz8hw.jpg",
    theBrief: "Demonstrate breadth of work and competence in regulated environments.",
    approachBullets: [
      "Real workplaces and authentic environments",
      "Authoritative tone",
      "Clarity and pace without gimmicks",
    ],
    tags: ["Recruitment", "H&S", "Logistics", "Warehousing"],
    year: 2023,
    featured: false,
    order: 26,
  },
  {
    id: "fb-027",
    slug: "banbury-lunchbox",
    title: "Banbury Lunchbox Community Project",
    client: "Banbury Lunchbox",
    sector: "Charity & Awareness",
    serviceType: "Brand & Corporate Films",
    description: "Local community Christmas initiative film",
    challenge: "Celebrate the impact of a local initiative bringing businesses together to support families in need at Christmas, and act as a call-to-action for next year's support.",
    approach: "Natural moments and authentic interactions, with warmth and community-first storytelling and an uplifting tone.",
    outcome: "Awareness and recruitment asset to help grow the initiative.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    vimeoId: null,
    thumbnailUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813461/lunchbox_2024_highlights.mp4_1080p_r9oqsq.jpg",
    cloudinaryVideoUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/v1744813461/lunchbox_2024_highlights.mp4_1080p_r9oqsq.mp4",
    cloudinaryPosterUrl: "https://res.cloudinary.com/drl0fxrkq/video/upload/so_0,w_800,h_450,c_fill,q_auto,f_jpg/v1744813461/lunchbox_2024_highlights.mp4_1080p_r9oqsq.jpg",
    theBrief: "Celebrate the impact and act as a call-to-action for next year's support.",
    approachBullets: [
      "Natural moments and authentic interactions",
      "Warmth and community-first storytelling",
      "Positive, uplifting tone",
    ],
    tags: ["Community", "Christmas", "Social impact", "Charity"],
    year: 2024,
    featured: false,
    order: 27,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getHeroProjects(): Project[] {
  return projects.filter((p) => p.hero === true);
}

export function getCaseStudyProjects(): Project[] {
  return projects.filter((p) => Boolean(p.theBrief));
}

export function getAllProjectTags(): string[] {
  const tags = new Set<string>();
  projects.forEach((p) => p.tags?.forEach((t) => tags.add(t)));
  return Array.from(tags);
}

export const services: Service[] = [
  {
    id: "1",
    slug: "brand-corporate-films",
    title: "Brand & Corporate Films",
    shortDescription: "Films that capture your essence, not just your messaging.",
    description: "Documentary-style brand films that reveal who you truly are. We go beyond surface-level messaging to capture the authentic character of your organisation.",
    icon: "Film",
    whoIsFor: "Marketing directors and brand managers who know their company is more than their competitors but struggle to communicate that difference authentically.",
    problemSolved: "Generic corporate videos feel interchangeable—polished but forgettable. They tell people what you do, but never show who you are.",
    whyFilmmakerLed: "Documentary techniques reveal authentic moments and genuine emotion. We create narrative structure that engages viewers, not just informs them.",
    whatMakesDifferent: "We spend time understanding your culture before we ever press record. Our films feature real people, real stories, and real moments that resonate.",
    deliverables: "Hero brand film (2-4 minutes), social cut-downs, behind-the-scenes content, strategy documentation",
    priceFrom: "£4,500",
    order: 1,
  },
  {
    id: "2",
    slug: "recruitment-employer-brand",
    title: "Recruitment & Employer Brand",
    shortDescription: "Attract talent with stories that ring true.",
    description: "Documentary-approach recruitment videos that showcase your genuine culture and attract candidates who'll thrive in your environment.",
    icon: "Users",
    whoIsFor: "HR directors and talent acquisition leaders competing for talent in tight labour markets where every company claims to be a 'great place to work'.",
    problemSolved: "Candidates see through scripted testimonials. Staged videos with employees reading from prompts feel fake—and talent knows it.",
    whyFilmmakerLed: "Documentary interview techniques draw out authentic stories. We create conditions where real employees share genuine experiences.",
    whatMakesDifferent: "We interview without scripts, finding the moments of genuine enthusiasm and honest reflection that convince candidates your culture is real.",
    deliverables: "Recruitment film (2-3 minutes), individual role spotlights, day-in-the-life content, LinkedIn-optimised cuts",
    priceFrom: "£3,500",
    order: 2,
  },
  {
    id: "3",
    slug: "documentary-case-studies",
    title: "Documentary-Style Case Studies",
    shortDescription: "Client success stories told with depth and credibility.",
    description: "Case study films that demonstrate your impact through authentic client stories, building trust and credibility with prospects.",
    icon: "BookOpen",
    whoIsFor: "B2B businesses with complex offerings where trust and proven results matter more than flashy promises.",
    problemSolved: "Written case studies lack emotional impact. Generic video testimonials feel rehearsed and fail to convey the full story of transformation.",
    whyFilmmakerLed: "We approach case studies as mini-documentaries, capturing the journey from challenge to solution to outcome with narrative structure.",
    whatMakesDifferent: "We interview both your team and your clients, weaving perspectives into a complete story that demonstrates value authentically.",
    deliverables: "Case study film (3-5 minutes), quote clips, prospect-specific edits, sales enablement content",
    priceFrom: "£3,000",
    order: 3,
  },
  {
    id: "4",
    slug: "presenter-coaching",
    title: "Presenter & Interviewee Coaching",
    shortDescription: "Prepare your team to shine on camera.",
    description: "Documentary filmmaker techniques applied to helping executives and team members communicate authentically and confidently on camera.",
    icon: "Mic",
    whoIsFor: "Leaders and team members who need to appear on camera but feel uncomfortable, stiff, or inauthentic when filmed.",
    problemSolved: "Most people hate being on camera. They become robotic, forget key messages, or look uncomfortable—undermining the content you're creating.",
    whyFilmmakerLed: "Documentary filmmakers specialise in making real people comfortable and authentic. We know how to draw out genuine presence.",
    whatMakesDifferent: "We use documentary interview techniques to help people find their natural voice, building confidence through practice and feedback.",
    deliverables: "One-on-one coaching sessions, group workshops, on-set support, preparation frameworks",
    priceFrom: "£800",
    order: 4,
  },
  {
    id: "5",
    slug: "event-motorsport-films",
    title: "Event & Motorsport Films",
    shortDescription: "Capturing the energy and drama of live moments.",
    description: "High-energy event coverage and motorsport documentation that captures the atmosphere, emotion, and key moments of your live events.",
    icon: "Zap",
    whoIsFor: "Event organisers, motorsport teams, and brands who want to extend the impact of their live events through compelling video content.",
    problemSolved: "Standard event coverage captures what happened, but misses the atmosphere and emotion. You need content that makes viewers wish they'd been there.",
    whyFilmmakerLed: "Documentary filmmakers capture authentic moments and human stories within the action. We find the narrative in the chaos.",
    whatMakesDifferent: "We go beyond coverage to storytelling—finding the characters, tensions, and resolutions that make events memorable.",
    deliverables: "Event highlight film, real-time social content, interview packages, promotional trailers",
    priceFrom: "£2,500",
    order: 5,
  },
];

export const sectors: Sector[] = [
  {
    id: "6",
    slug: "food-hospitality",
    title: "Food & Hospitality",
    shortDescription: "Capturing the craft, passion, and stories behind food and hospitality brands.",
    description: "Food and hospitality businesses thrive on authenticity and craft. Documentary-style video captures the passion, skill, and human stories that make your brand memorable.",
    industryKnowledge: "In an era of artisan food movements and farm-to-table dining, customers want to know the story behind what they eat. They're seeking genuine connections with the people who make their food.",
    whyDocumentaryWorks: "Documentary approach reveals the craft and dedication behind every dish. We capture the early mornings, the precise techniques, and the pride that goes into artisan production.",
    experience: "We've worked with bakeries, restaurants, and food producers to create content that showcases their authentic story and connects with food-loving audiences.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    order: 1,
  },
  {
    id: "1",
    slug: "recruitment-employer-branding",
    title: "Recruitment & Employer Branding",
    shortDescription: "Authentic employer brand content that attracts talent who'll thrive.",
    description: "In today's competitive talent market, authentic employer branding is essential. We help organisations cut through the noise with genuine employee stories.",
    industryKnowledge: "The recruitment landscape has fundamentally changed. Candidates research employers thoroughly before applying, and they can spot inauthenticity instantly. Generic 'great place to work' messaging no longer convinces anyone.",
    whyDocumentaryWorks: "Candidates see through scripted testimonials. Documentary approach draws out genuine employee stories that resonate because they're real. We create conditions for authentic sharing, not rehearsed performances.",
    experience: "We've produced 50+ recruitment videos for organisations across sectors, from logistics firms to tech startups. Our clients report an average 40% increase in quality applications.",
    testimonial: "Rob played a pivotal role in our recruitment content production. He took the time to engage with every participant, making those who felt apprehensive comfortable in front of the camera.",
    testimonialAuthor: "Ronnee Muldoon",
    testimonialRole: "Recruitment, Smyths Toys",
    order: 2,
  },
  {
    id: "2",
    slug: "financial-services",
    title: "Financial Services",
    shortDescription: "Compliant, compelling video for regulated industries.",
    description: "Financial services face unique challenges: regulatory requirements, complex products, and the need to build trust in an industry often viewed with scepticism.",
    industryKnowledge: "FCA Consumer Duty requirements now mandate clear communication. Generic videos don't meet compliance standards, and overly technical content fails to engage clients.",
    whyDocumentaryWorks: "Documentary approach humanises financial services. We capture real client relationships and genuine expertise, making complex topics accessible while maintaining credibility.",
    experience: "We've worked with wealth managers, insurance providers, and fintech firms. Our content achieves 2x higher engagement than industry benchmarks while meeting compliance requirements.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    order: 2,
  },
  {
    id: "3",
    slug: "manufacturing-health-safety",
    title: "Manufacturing & Health Safety",
    shortDescription: "Showcasing craftsmanship and safety excellence.",
    description: "Manufacturing businesses need to demonstrate quality, precision, and safety. Documentary approach captures the expertise and dedication that define manufacturing excellence.",
    industryKnowledge: "Manufacturing faces perception challenges: automation concerns, skills gaps, and the need to attract younger workers. Video must showcase the craft and innovation that define modern manufacturing.",
    whyDocumentaryWorks: "Documentary filmmaking captures the pride and precision of manufacturing work. We show the human expertise behind every process, building appreciation for craftsmanship.",
    experience: "We've documented manufacturing processes from precision engineering to food production. Our films become sales tools that directly contribute to contract wins.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    order: 3,
  },
  {
    id: "4",
    slug: "motorsport",
    title: "Motorsport",
    shortDescription: "The drama, dedication, and human stories behind racing.",
    description: "Motorsport is drama, dedication, and split-second decisions. Based near Silverstone in Motorsport Valley, we understand the culture and stories that make racing compelling.",
    industryKnowledge: "Motorsport content needs to go beyond race highlights. Sponsors want to see their values reflected; fans want access to the human stories behind the helmets.",
    whyDocumentaryWorks: "Documentary approach captures the intensity and human drama that makes motorsport compelling. We find the stories within the action, the characters within the competition.",
    experience: "From British GT to grassroots racing, we've documented teams across motorsport. Our content increases sponsor engagement and attracts new partnerships.",
    testimonial: "Collaborating with Flashbuzz for our events is consistently a rewarding experience. Their exceptional editing skills and meticulous attention to detail result in a polished final product that truly enhances our storytelling.",
    testimonialAuthor: "HERO ERA Team",
    testimonialRole: "Webmaster, HERO ERA",
    order: 4,
  },
  {
    id: "5",
    slug: "scientific-tech",
    title: "Scientific & Tech",
    shortDescription: "Making complex innovation accessible and compelling.",
    description: "Scientific and technology organisations face the challenge of communicating complex ideas to diverse audiences—investors, partners, customers, and the public.",
    industryKnowledge: "Tech and science content often falls into two traps: oversimplifying to the point of inaccuracy, or remaining so technical that non-experts switch off. Neither builds trust.",
    whyDocumentaryWorks: "Documentary approach brings out the passion behind innovation. We help scientists and technologists share their work in ways that inspire without compromising accuracy.",
    experience: "We've worked with biotech firms, research institutions, and tech startups. Our content helps secure funding, attract talent, and build public understanding.",
    testimonial: null,
    testimonialAuthor: null,
    testimonialRole: null,
    order: 5,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote: "Rob's professionalism and creative vision are remarkable. He has a unique ability to bring out the best in everyone — fostering confidence and a positive attitude on every shoot.",
    author: "Kathryn Ennis-Burton",
    role: "National Sales Manager",
    company: "Tugo Food Systems",
    sector: "Food & Hospitality",
    featured: true,
    order: 1,
    // Original (Mar 2026): "After meeting with Rob to discuss the production of a series of short films for Tugo Food Systems, I recently had the opportunity to collaborate with him on-site for filming a series of advertisements. Rob's professionalism and expertise have left me with profound admiration for his craft. He possesses a remarkable creative vision while maintaining a calm and friendly demeanor in every situation. Working alongside Rob is truly inspiring; he has a unique ability to bring out the best in everyone, fostering confidence and a positive attitude."
  },
  {
    id: "2",
    quote: "Rob played a pivotal role in our recruitment content production. He took the time to engage with every participant, making those who felt apprehensive comfortable in front of the camera. It's clear Rob is passionate about his craft, and that shows in the work.",
    author: "Ronnee Muldoon",
    role: "Recruitment",
    company: "Smyths Toys",
    sector: "Recruitment & Employer Branding",
    featured: true,
    order: 2,
    // Original (Mar 2026): "Rob played a pivotal role in our recruitment content production. On the day of the shoot, he took the time to engage with all participants, ensuring that those who felt apprehensive were made comfortable in front of the camera. Upon receiving the footage, Rob was open to feedback and made adjustments to the clips to align with our vision. It is clear that Rob is passionate about his craft, and this enthusiasm is reflected in the quality of his work."
  },
  {
    id: "3",
    quote: "Collaborating with Flashbuzz for our events is consistently a rewarding experience. Their exceptional editing skills and meticulous attention to detail result in a polished final product that truly enhances our storytelling.",
    author: "HERO ERA Team",
    role: "Webmaster",
    company: "HERO ERA",
    sector: "Motorsport",
    featured: true,
    order: 3,
    // Original quote attributed to "Anonymous" in DB; using company-level attribution. Original: "Collaborating with Flashbuzz for our events is consistently a rewarding experience. Their exceptional editing skills and meticulous attention to detail result in a polished final product that truly enhances our storytelling."
  },
  {
    id: "4",
    quote: "Rob crafted a heartwarming film that perfectly encapsulated the ethos and personality of our hospice. His thoughtful approach to our vulnerable patients ensured the experience was enjoyable for everyone involved. An exceptionally professional and creative film.",
    author: "Karen Welsh",
    role: "Marketing Manager",
    company: "Katharine House Hospice",
    sector: "Charity & Healthcare",
    featured: false,
    order: 4,
    // Original (Mar 2026): "I wholeheartedly recommend FlashBuzz Video! Rob expertly produced a remarkable promotional video for Katharine House Hospice in Banbury, offering invaluable guidance and support throughout the entire process. He crafted a heartwarming film that perfectly encapsulated the ethos and personality of our hospice. His thoughtful approach to our vulnerable patients ensured that the experience was enjoyable for everyone involved. The final product was an exceptionally professional and creative film that showcased the range of services we provide, as well as the hope and happiness we strive to deliver. Remarkably, he did all of this pro bono!"
    // NOTE: pro bono mention deliberately omitted — for B2B prospects this can read as "he should do it cheap for me." If you want the pro bono fact surfaced, it goes on the about page as character context, not on a testimonial.
  },
  {
    id: "5",
    quote: "Rob captured the emotional essence of our campaign issue, despite lacking personal experience in the subject matter. Truly an expert. Professionalism, an approachable demeanor on set, and a swift turnaround on editing.",
    author: "Andie Vilela",
    role: "Campaign Lead",
    company: "Redwings Horse Sanctuary",
    sector: "Charity & Awareness",
    featured: false,
    order: 5,
    // Original (Mar 2026): "I greatly appreciate Rob's professionalism, his approachable demeanor on set, and the swift turnaround on editing. He adeptly captured the emotional essence of our campaign issue, despite lacking personal experience in the subject matter—truly an expert!"
    // NOTE: role inferred from context — Andie's actual title not in DB. Confirm with Rob before launch.
  },
  {
    id: "6",
    quote: "Rob's warm demeanor and professionalism stood out from the very first meeting. We're thrilled with the outcome of the video and images. I wholeheartedly recommend Rob and the talented team at Flashbuzz.",
    author: "Nadine Griffin",
    role: "Managing Director",
    company: "Flutter Shutter",
    sector: "Cleantech & Innovation",
    featured: false,
    order: 6,
    // Original (Mar 2026): "We engaged Rob from FlashBuzz Video to capture a pivotal installation project for our company, Flutter Shutter. From our very first meeting, Rob's warm demeanor and professionalism stood out. We quickly established a rapport, and throughout the day, we shared countless laughs between filming takes. We are thrilled with the outcome of the video and images, and we eagerly anticipate sharing them on our social media platforms."
  },
  {
    id: "7",
    quote: "Rob produced an exceptional company video that effectively showcases our boutique HR recruitment agency. The entire process was enjoyable from beginning to end, and Rob consistently went above and beyond.",
    author: "Katie Barnicoat",
    role: "Director",
    company: "Peeq",
    sector: "Recruitment",
    featured: false,
    order: 7,
    // Original (Mar 2026): "We had the distinct pleasure of collaborating with Rob from FlashBuzz, and we are absolutely thrilled with the outcome! He produced an exceptional company video that effectively showcases our boutique HR recruitment agency, capturing the essence and charm of our small, family-run business. The entire process was enjoyable from beginning to end, and Rob consistently went above and beyond to ensure we secured the perfect shots for a polished, professional video."
  },
  {
    id: "8",
    quote: "Working with Flashbuzz and Rob has been an exceptional experience. Their professionalism and commitment to delivering high-quality videos is commendable. Impressively swift turnaround from shoot to final edit.",
    author: "Robert Allen-Pugh",
    role: "Project Lead",
    company: "Warmfront",
    sector: "Public Sector & Property",
    featured: false,
    order: 8,
    // Original (Mar 2026): "Working with FlashBuzz and Rob has been an exceptional experience. Their professionalism and commitment to delivering high-quality videos for business promotional purposes are commendable. The turnaround time from shooting to final edit was impressively swift, and they addressed all inquiries and adjustments with remarkable efficiency."
  },
];

export const journalPosts: JournalPost[] = [
  {
    id: "1",
    slug: "why-documentary-approach-works-for-business",
    title: "Why Documentary Approach Works for Business Video",
    excerpt: "Generic corporate video fails because it treats businesses like products to be advertised. Documentary approach treats them as stories to be told.",
    content: "Full article content here...",
    category: "Documentary Technique",
    readTime: 5,
    published: true,
    createdAt: new Date("2024-12-15"),
  },
  {
    id: "2",
    slug: "interview-techniques-for-authentic-testimonials",
    title: "Interview Techniques for Authentic Testimonials",
    excerpt: "The difference between a rehearsed testimonial and a genuine one isn't script versus no script—it's how you create the conditions for authenticity.",
    content: "Full article content here...",
    category: "Behind the Scenes",
    readTime: 7,
    published: true,
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "3",
    slug: "recruitment-video-mistakes-to-avoid",
    title: "5 Recruitment Video Mistakes That Drive Candidates Away",
    excerpt: "Most recruitment videos fail because they tell candidates what the company wants them to hear, not what they need to know.",
    content: "Full article content here...",
    category: "Industry Insights",
    readTime: 6,
    published: true,
    createdAt: new Date("2024-11-20"),
  },
];

export const clientLogos = [
  { 
    name: "Bibby Financial Services", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/BFS-logo_luy7i9" 
  },
  { 
    name: "John Lewis", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/John_Lewis___Partners_logo_dsgh4o" 
  },
  { 
    name: "Overbury", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/Overbury-Logo_f2fygl" 
  },
  { 
    name: "Subaru", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/Subaru-Logo-9-1200x750_rjjb2z" 
  },
  { 
    name: "Tugo Foods", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/TUGO_logo_large_black_on_red_podyxc" 
  },
  { 
    name: "Smyths Toys", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/channels4_profile_pymxmk" 
  },
  { 
    name: "Voneus", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/download_1_irerko" 
  },
  { 
    name: "Halfords", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/halfords-logo_dhdbym" 
  },
  { 
    name: "Hero Era", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/images_wudq1a" 
  },
  { 
    name: "Prodrive", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/stickers-prodrive_waldqo" 
  },
  { 
    name: "Spring Chicken", 
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/unnamed_hpxlbb" 
  },
  {
    name: "White Stuff",
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/white-stuff-primary-logo-black-gfvuxfgydsubdeaax-yr4vn2lm-2023-10-30_jrynah"
  },
  // TODO: Add Doorfit logo when available — currently using thumbnail crop as a placeholder is acceptable, but ideally a clean logo PNG should be uploaded.
  {
    name: "Doorfit",
    logo: "https://res.cloudinary.com/drl0fxrkq/image/upload/w_240,h_100,c_pad,b_white,q_auto,f_auto/Doorfit_48_k6ls8g",
  },
];

export { pricingTiers, secondaryOffers } from "./pricing";
