import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageMeta } from "@/components/page-meta";
import { FILM_WORKSHOP } from "@/lib/workshopLinks";

export default function WorkshopFilm() {
  const link = FILM_WORKSHOP;
  const ctaHref = link.status === "live" ? link.url! : link.waitlistUrl!;
  const ctaLabel = link.status === "live" ? "Register for the workshop" : "Join the waitlist";
  const ctaTarget = link.status === "live" ? "_blank" : undefined;
  const ctaRel = link.status === "live" ? "noopener noreferrer" : undefined;

  return (
    <div className="min-h-screen pt-24 lg:pt-32">
      <PageMeta
        title="Workshop: How to waste £25k on a brand film | Flashbuzz"
        description="A free 60-minute workshop for UK marketing directors. The brand film diagnostic that prevents your next £25k commission from underperforming. Hosted by Rob Hutt, 27-time award-winning documentary filmmaker."
        canonical="https://flashbuzz.tv/workshop/brand-film"
      />
      <section className="py-16 lg:py-24">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <div>
            <h1 className="text-4xl lg:text-5xl font-bold text-foreground mb-6">How to waste £25k on a brand film</h1>
            <p className="text-xl text-muted-foreground leading-relaxed mb-8">What your audience really cares about, and how to make sure your next brand film actually finds it. A free workshop for UK marketing directors and senior marketing leads. Workshop launching soon. Join the waitlist to be the first to know when registration opens.</p>
            <a href={ctaHref} target={ctaTarget} rel={ctaRel} className="plausible-event-name=Film+Workshop+Register+Click" data-testid="film-workshop-register-hero"><Button size="lg">{ctaLabel}<ArrowRight className="w-4 h-4 ml-2" /></Button></a>
          </div>
          <div className="aspect-[4/3] rounded-lg overflow-hidden bg-muted">
            <img src="https://i.vimeocdn.com/video/1713895958-66ce5480baf7a32d94908aef282d956810e208d061bd2371813ad28f9c9ad844-d_640" alt="Flashbuzz brand film workshop supporting image" className="w-full h-full object-cover" loading="eager" />
          </div>
        </div>
      </section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">The £25k brand film is wasted six months before the board sees it</h2><p>A marketing director sits in front of a board, presenting the metrics from a £25k brand film commissioned six months earlier. The film is technically excellent. The production agency was reputable. The brief looked sound when it was written. The metrics are flat. The board is asking what they got for the spend, and the marketing director is defending the work.</p><p>The £25k wasn't wasted in the production. The cameras turned on, the talent performed, the edit landed, the colour grade was correct. The £25k was wasted six months earlier, when the brief was being written. The brief described what the business did instead of what the audience actually cared about, and no production agency in the world could have rescued the resulting film from being commercially invisible.</p><p>Most brand films at the £18k–£50k tier waste money for this single reason. The workshop teaches a CharacterX-derived diagnostic that distinguishes brand films that find what the audience cares about from brand films that just describe what the business is. The methodology applies before the brief is written, during treatment review, and after the film is delivered as a post-mortem. Whether you commission the resulting work with Flashbuzz, with your existing agency, or in-house, the diagnostic prevents the wasted spend.</p><p>It's free, runs for 60 minutes, and you'll leave with the diagnostic applied live to a brand film you've recently commissioned, are about to commission, or are evaluating in the approval chain.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What you'll leave with</h2><p>The CharacterX audience diagnostic applied live to a real brand film project — a brief, a treatment, a rough cut, or a finished film you're trying to assess. You'll see exactly where the £25k is at risk, which of the three failure modes is most acute, and what the priority intervention is.</p><p>A five-part pressure test you can run on every brand film brief, treatment, and final cut to determine whether it's actually answering what the audience cares about. The test takes 30 minutes per film and applies whether you're commissioning, approving, or assessing.</p><p>The three most common reasons brand films waste money at this tier, with specific interventions that prevent each one. Worked examples drawn from the Flashbuzz portfolio and from named productions in the wider industry that demonstrate each failure mode at scale.</p><p>The signs that distinguish a brand film commission from a strategy problem disguised as a brand film commission, with a clear next-step recommendation for each. Some projects shouldn't be brand film commissions at all, and the workshop is honest about which ones — including the cases where Flashbuzz wouldn't be the right supplier even if you wanted to commission us.</p><p>A working understanding of why most production agencies can't help with this question, and what kind of supplier relationship to look for when the strategic stakes are higher than the production stakes.</p></div></section>

      <section className="py-14 border-y border-border/60 bg-card"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What the workshop teaches</h2><p>Most £25k brand film waste traces back to one of three failure modes. The workshop walks through each one with worked examples from real productions, including the HERO ERA Peking to Paris build-up film that ran as editorial rather than corporate at the brief's insistence, and the Catherine House Hospice awareness film that approached end-of-life care with the dignity the subject demanded rather than defaulting to category convention.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 1: The brief that mistakes category for audience</h3><p>Most enterprise briefs describe the audience by demographic and the system by industry. Both are surface-level. The audience isn't a 35–55 year old decision-maker. The system isn't <em>the modern business landscape</em>. The fix: the audience is a specific person in a specific moment of their working week, navigating a specific frustration that your business solves. The system is what they've already tried, ruled out, or learned to live with. The workshop walks through the structural rewrite with worked examples.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 2: The brief that delegates the strategic question to the supplier</h3><p>Most marketing directors hand over briefs that ask the production agency to figure out the emotional shape of the film. <em>Premium, distinctive, memorable.</em> That sentence guarantees the agency hedges toward category convention because they have no other anchor. The fix: the marketing director names the specific recognition the audience should feel watching the film, and the brief makes that recognition the success criterion. Worked examples show three rewrites of the same brief producing structurally different films.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 3: The brief that should have been a Discovery</h3><p>Some brand film commissions aren't really brand film commissions. They're strategy questions disguised as content briefs. A repositioning. A response to a competitor. A rebrand following a leadership change. A pivot into a new market. No brief template can solve a strategic question, and the £25k spent on a film that should have been a strategic engagement is the most expensive form of waste at this tier. The workshop teaches how to spot the difference, with the honest note that some attendees will leave realising their project should not be a film commission at all.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who this is for</h2><p>Marketing directors, senior marketing leads, brand directors, and CMOs at UK companies turning over £20m to £100m. You commission brand films at the £18k to £50k tier as part of your strategic remit. You report into a board, a CEO, or both, and the films you commission are visible enough that underperformance has consequences for your internal credibility.</p><p>Right now, one of four things is true. You've just commissioned a brand film that underperformed and the board is asking why. You're about to commission one and the spend is keeping you up. You're approving one in the chain and aren't confident the brief is right. Or you've been asked by senior leadership to deliver brand work and aren't sure what you're actually being asked for. The workshop is calibrated to all four states.</p></div></section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who's running it</h2><p>The workshop is built and hosted by Rob Hutt of Flashbuzz. Rob is a 27-time international award-winning documentary filmmaker. His narrative short <em>Time Spent</em> holds an 8.8 IMDb rating and won 27 international awards. He taught at the Film and Television Academy for several years before returning to commercial filmmaking full time, and he photographed the recent Auto Addicts magazine feature on Alastair Caldwell, the McLaren team manager from the Hunt-Lauda era depicted in Ron Howard's <em>Rush</em>. His brand film work for UK businesses includes HERO ERA, Bibby Financial Services, Catherine House Hospice, and engagements across recruitment, hospitality, financial services, and charity sectors since 2014.</p><p>The workshop runs on the Flashbuzz workshop platform, with delivery handled by Norman, the AI host. Norman guides each attendee through the workshop independently, with the diagnostic tool slide returning a personalised CharacterX read on whichever brand film project the attendee submits — a brief, a treatment, a rough cut, or a finished film. The cumulative engagement model means later attendees see the running tally of which failure modes have been most common across all submitted projects, building shared diagnostic experience over time.</p></div></section>

      <section className="py-16 lg:py-20"><div className="max-w-4xl mx-auto px-6 lg:px-8"><h2 className="text-3xl font-bold text-foreground mb-6">Join the waitlist</h2><div className="space-y-6 text-lg text-muted-foreground mb-8"><p>The workshop is free to attend. Register through the Flashbuzz workshop platform and you'll get immediate access — every attendee runs through the workshop independently, on their own schedule, with Norman guiding them through. You'll receive your project diagnostic immediately and a follow-up email at day seven offering a free written CharacterX strategic review on your actual project, delivered within seven working days.</p><p>The strategic review is calibrated to be genuinely useful as an independent strategic asset, equivalent to a £1k–£2k consulting deliverable in the open market. The review tells you whether the project is on track, what the priority intervention is, and which of the three failure modes is most acute. Whether you commission the resulting work with Flashbuzz, with your existing agency, or in-house, the diagnostic does the same job: makes sure the £25k spend doesn't end with you defending the result to your board.</p></div><a href={ctaHref} target={ctaTarget} rel={ctaRel} className="plausible-event-name=Film+Workshop+Register+Click" data-testid="film-workshop-register-footer"><Button size="lg">{ctaLabel}<ArrowRight className="w-4 h-4 ml-2" /></Button></a></div></section>
    </div>
  );
}
