import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageMeta } from "@/components/page-meta";
import { PHOTOGRAPHY_WORKSHOP } from "@/lib/workshopLinks";

export default function WorkshopPhotography() {
  const link = PHOTOGRAPHY_WORKSHOP;
  const ctaHref = link.status === "live" ? link.url! : link.waitlistUrl!;
  const ctaLabel = link.status === "live" ? "Register for the workshop" : "Join the waitlist";
  const ctaTarget = link.status === "live" ? "_blank" : undefined;
  const ctaRel = link.status === "live" ? "noopener noreferrer" : undefined;

  return (
    <div className="min-h-screen pt-24 lg:pt-32">
      <PageMeta
        title="Workshop: Losing customers to big-name chains? | Flashbuzz"
        description="A free 60-minute workshop for UK small business owners. The visual mistake costing you bookings and the simple shift that turns the tables. Hosted by Rob Hutt, 27-time award-winning documentary filmmaker."
        canonical="https://flashbuzz.tv/workshop/small-business-photography"
      />

      <section className="py-16 lg:py-24">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <div>
            <h1 className="text-4xl lg:text-5xl font-bold text-foreground mb-6">Losing customers to big-name chains?</h1>
            <p className="text-xl text-muted-foreground leading-relaxed mb-8">The visual mistake costing you bookings, and the simple shift that turns the tables. A free workshop for UK small business owners.</p>
            <a href={ctaHref} target={ctaTarget} rel={ctaRel} className="plausible-event-name=Photo+Workshop+Register+Click" data-testid="photo-workshop-register-hero">
              <Button size="lg">{ctaLabel}<ArrowRight className="w-4 h-4 ml-2" /></Button>
            </a>
          </div>
          <div className="aspect-[4/3] rounded-lg overflow-hidden bg-muted">
            <img src="https://res.cloudinary.com/drl0fxrkq/image/upload/q_auto,f_auto,w_1200/P1011262_ooaj27" alt="Flashbuzz small business photography commission" className="w-full h-full object-cover" loading="eager" />
          </div>
        </div>
      </section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Your photographs are losing you customers, and you probably don't know it</h2><p>Walk past any high street in the UK and look at the difference between the chain's storefront and the independent's. The chain has consistent professional photography on their windows, their menus, their website, their social. The independent has a mix of mobile phone snaps, photographs from three different shoots taken across two years, and stock images of strangers used because the real photographs felt too amateur to put on the homepage.</p><p>The chain isn't winning because they're better at running a business. In most cases, they're worse. The chain wins because their photographs make them look trustworthy at the moment a customer is deciding where to spend money. Your photographs are doing the opposite, and you're losing bookings because of it.</p><p>This workshop teaches the visual shift that closes the gap. It's free, runs for 60 minutes, and you'll leave with a clear diagnostic on your own current photography and a four-pillar checklist for fixing it. You'll also leave understanding why the small business has an asymmetric advantage over the chain on photography that most independents never think to use.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What you'll leave with</h2><p>A diagnostic on your current photography, applied live to your own website during the workshop. You'll see exactly where your photographs are working and where they're costing you customers, in real time, with personalised output for your specific business.</p><p>A four-pillar checklist you can use on every future photograph you commission, take, or post. Trust, story, consistency, repurposing. Each one diagnosable in 30 seconds. Each one fixable.</p><p>The four photographs every small business needs, and the order to commission them in. No vague advice. Specific photographs, specific purposes, specific reasons each one outperforms what most independents currently have.</p><p>The arithmetic that makes professional photography the highest-impact marketing investment a small business can make. By the end of the workshop, you'll be able to do the back-of-envelope calculation yourself for your own business, including the per-asset cost across a six-month repurposing window.</p><p>A clear understanding of when your business is ready to graduate from photography-first to video, what kind of video to commission first, and how to spot the moment when that transition is the right move.</p></div></section>

      <section className="py-14 border-y border-border/60 bg-card"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What the workshop teaches</h2><p>Most small business photography fails at four specific jobs. The workshop walks through each one with examples from real Flashbuzz commissions, including small business work like Suzie's Pets dog grooming and the recent Auto Addicts magazine feature with former McLaren team manager Alistair Caldwell.</p><h3 className="text-2xl font-semibold text-foreground">Pillar 1: Builds trust</h3><p>Real photographs beat stock photographs. Professional real photographs beat amateur real photographs. The trust mechanic is structural: photographs that show your business in the act of serving a customer build more trust than photographs that show who your business is. Most small business photography fails this pillar. The workshop teaches the specific shift that fixes it.</p><h3 className="text-2xl font-semibold text-foreground">Pillar 2: Tells a story</h3><p>Every photograph should answer one question: whose story is this? If the answer is your business's story, the photograph is doing the wrong job. If the answer is your customer's story, with your business in the role of trusted guide, the photograph is doing the right job. The workshop walks through worked examples showing the same image with two completely different framings, and how the right one converts where the wrong one doesn't.</p><h3 className="text-2xl font-semibold text-foreground">Pillar 3: Creates a consistent look and feel</h3><p>Most small businesses have a graveyard of photographs taken by different people, on different days, in different light. The result is visual chaos. The workshop teaches why one shoot day fixes it, and why consistency, not quality, is what makes a small business look like a business rather than a hobbyist with a phone.</p><h3 className="text-2xl font-semibold text-foreground">Pillar 4: Repurposes for social and blogs</h3><p>The most overlooked pillar and the one with the highest return. One shoot day produces 30+ usable assets across a six-month content cycle. Most small businesses commission a photography day, use the headshots once, and never touch the rest. The workshop teaches the repurposing maths that makes professional photography genuinely the lowest-cost, highest-impact marketing move available.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who this is for</h2><p>UK small business owners and founders running B2C local independents. Owner-operators, sole traders, small teams. If you run a café, a salon, a shop, a service business, a clinic, a studio, a small practice, you're the audience. If you've ever looked at a competing chain's photography and felt slightly defeated, you're the audience.</p><p>The workshop is calibrated to businesses turning over under £2m where the marketing function is the founder or one team member. It's not for marketing managers at larger businesses, who have their own workshop calibrated to their level. It's not for hobbyist photographers looking for craft tips, who would be better served by a craft-focused course. It's for owners who need their photography to win them more customers, faster, with less spend than chains have to throw at the same problem.</p></div></section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who's running it</h2><p>The workshop is built and hosted by Rob Hutt of Flashbuzz. Rob is a 27-time international award-winning documentary filmmaker, former Film and Television Academy tutor, and the photographer behind the recent Auto Addicts magazine feature on Alastair Caldwell, the McLaren team manager from the Hunt-Lauda era depicted in Ron Howard's <em>Rush</em>. He's been making brand films and commercial photography for UK businesses since 2014.</p><p>The workshop runs on the Flashbuzz workshop platform, with delivery handled by Nora, the AI host. Nora guides each attendee through the workshop independently, with the diagnostic tool slide returning a personalised CharacterX read on each attendee's current photography. Every attendee sees the running tally of how previous attendees scored on the four pillars, building social proof and shared diagnostic experience over time.</p></div></section>

      <section className="py-16 lg:py-20"><div className="max-w-4xl mx-auto px-6 lg:px-8"><h2 className="text-3xl font-bold text-foreground mb-6">Register for the workshop</h2><div className="space-y-6 text-lg text-muted-foreground mb-8"><p>The workshop is free to attend. Register through the Flashbuzz workshop platform and you'll get instant access — every attendee runs through the workshop independently, on their own schedule, with the AI host guiding them through. You'll receive your diagnostic results immediately and a follow-up email at day five with deeper analysis applied to your specific business.</p><p>Workshop attendees who book a Flashbuzz photography day within 14 days of completing the workshop receive a £100 discount on the booking, with the workshop fee credited in full.</p></div><a href={ctaHref} target={ctaTarget} rel={ctaRel} className="plausible-event-name=Photo+Workshop+Register+Click" data-testid="photo-workshop-register-footer"><Button size="lg">{ctaLabel}<ArrowRight className="w-4 h-4 ml-2" /></Button></a></div></section>
    </div>
  );
}
