import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageMeta } from "@/components/page-meta";

const registrationUrl = "{{VIDEO_WORKSHOP_URL}}";

export default function WorkshopVideo() {
  return (
    <div className="min-h-screen pt-24 lg:pt-32">
      <PageMeta
        title="Workshop: When your next video has to actually work | Flashbuzz"
        description="A free 60-minute workshop for UK marketing managers. The brief diagnostic that prevents your next £4k–£15k video from underperforming. Hosted by Rob Hutt, 27-time award-winning documentary filmmaker."
        canonical="https://flashbuzz.tv/workshop/video-brief"
      />
      <section className="py-16 lg:py-24">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <div>
            <h1 className="text-4xl lg:text-5xl font-bold text-foreground mb-6">When your next video has to actually work</h1>
            <p className="text-xl text-muted-foreground leading-relaxed mb-8">The brief diagnostic that makes sure your next campaign, launch, or pitch video doesn't underperform when the stakes are highest. A free workshop for UK marketing managers and comms leads.</p>
            <a href={registrationUrl} target="_blank" rel="noopener noreferrer" className="plausible-event-name=Video+Workshop+Register+Click" data-testid="video-workshop-register-hero"><Button size="lg">Register for the workshop<ArrowRight className="w-4 h-4 ml-2" /></Button></a>
          </div>
          <div className="aspect-[4/3] rounded-lg overflow-hidden bg-muted">
            <img src="https://i.vimeocdn.com/video/1852754909-203ae33b118f2514cf59c35dae845d8bfbfc82717baeded0c4faf116c44c05b0-d_640" alt="Flashbuzz video workshop supporting image" className="w-full h-full object-cover" loading="eager" />
          </div>
        </div>
      </section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">The brief is where most £4k–£15k videos go wrong</h2><p>Most marketing managers commission video that's executed competently and disappears commercially. The supplier wasn't lazy. The agency wasn't bad. The brief was generic, and a generic brief produces generic video that looks like every other video in the category. In calm conditions, this is annoying but survivable. The video doesn't move the needle, the campaign underperforms by a margin you can explain away, and you commission another one next quarter hoping for a different result.</p><p>The problem comes when the stakes spike. A product launch where the video is the centrepiece. A campaign that has to deliver against last quarter's underperformance. A pitch supporting asset where you can't afford to look generic. A response to a competitor who just released something specific and credible. In those moments, the same brief template that produced fine results in calm conditions produces a video that visibly fails in front of an audience that matters.</p><p>This workshop teaches the brief-shaping discipline that prevents that failure. It's free, runs for 60 minutes, and you'll leave with a CharacterX diagnostic applied to your own actual upcoming video brief, plus a four-question pressure test you can run on every brief you write or approve from now on.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What you'll leave with</h2><p>A diagnostic applied live to your actual upcoming video brief. Not a hypothetical brief. Not last year's brief. The brief on your desk right now for the project that has to actually work. You'll see exactly which sentences are generic, where the protagonist-and-system framing is broken, and which of the three failure modes is most acute in your specific case.</p><p>A four-question pressure test you can run on every future brief in 10 minutes, before sending it to a supplier. The test catches the structural weaknesses that produce generic video, before the £4k–£15k engagement gets started.</p><p>The three brief-writing failure modes that produce category-look-alike video, with specific rewrites for each one. Worked examples showing the same brief structurally improved in three different ways, and the structurally different videos each rewrite would produce.</p><p>A working understanding of why most production agencies can't help you reshape the brief — they execute briefs, they don't reshape them — and what kind of supplier relationship to look for when the stakes are higher than usual.</p><p>The signs that tell you when a project has outgrown brief-led video and warrants a strategic engagement instead. Some videos fail because the brief was wrong. Some fail because no brief could have fixed it. The workshop teaches the difference.</p></div></section>

      <section className="py-14 border-y border-border/60 bg-card"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">What the workshop teaches</h2><p>Most generic video traces back to one of three brief-writing failure modes. The workshop walks through each one with worked examples drawn from the Flashbuzz portfolio, including the Bibby Financial Services recruitment work that ran on laughter and outtakes when the standard brief would have produced something corporate, and the HERO ERA Peking to Paris film that found editorial cut-through where the brief originally called for a corporate build-up piece.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 1: Describing what you do instead of the role you play</h3><p>Most briefs open with a paragraph about the business. <em>We're a [category] company that helps [audience] do [outcome].</em> That sentence produces video that's invisible the moment a competitor releases something specific. The workshop teaches the structural rewrite that fixes it: describe the role you play in the customer's situation, not the activity you perform.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 2: Generic protagonist, generic system</h3><p>Most briefs describe a generic customer doing generic things. Demographics, vague psychographics, <em>typical buyer</em> descriptions that could apply to any business in your category. That sentence is the death of distinctive video and the first thing that fails when a campaign needs to convert. The fix is the CharacterX protagonist-and-system diagnostic applied to the brief: a specific customer in a specific moment, navigating a specific frustration, considering specific alternatives.</p><h3 className="text-2xl font-semibold text-foreground">Failure mode 3: Asking the supplier to make it engaging without naming the specific feeling</h3><p>Most briefs delegate the emotional shape of the video to the supplier. <em>Premium, distinctive, memorable.</em> That phrasing guarantees the supplier hedges toward category convention because they have nothing else to anchor against. The workshop teaches how to name the specific recognition the video should produce in the viewer, with worked examples showing the same brief producing structurally different films depending on how the emotional brief is written.</p></div></section>

      <section className="py-14"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who this is for</h2><p>Marketing managers, comms leads, content leads, and senior marketing executives at UK companies turning over £2m to £10m. You commission video as part of your job. You have a budget, typically £3k to £15k per video, and a quarterly KPI to hit. You've worked with at least one production company before and at least one of those engagements produced a video you were privately disappointed by.</p><p>Right now, you have a specific upcoming video project where the stakes are higher than usual. A product launch in six weeks. A campaign that has to deliver against last quarter's underperformance. A pitch supporting asset for a tier you haven't won before. A response to a competitor who just released something specific. You're not browsing this workshop for theory. You're attending because the brief on your desk has to hold up under pressure, and you're not confident it will.</p></div></section>

      <section className="py-14 border-y border-border/60"><div className="max-w-4xl mx-auto px-6 lg:px-8 space-y-6 text-lg text-muted-foreground"><h2 className="text-3xl font-bold text-foreground">Who's running it</h2><p>The workshop is built and hosted by Rob Hutt of Flashbuzz. Rob is a 27-time international award-winning documentary filmmaker, former Film and Television Academy tutor, and the photographer behind the recent Auto Addicts magazine feature on Alastair Caldwell. His brand film work for UK businesses includes HERO ERA, Bibby Financial Services, and Catherine House Hospice, with films and videos commissioned across recruitment, hospitality, financial services, and charity sectors since 2014.</p><p>The workshop runs on the Flashbuzz workshop platform, with delivery handled by Norman, the AI host. Norman guides each attendee through the workshop independently, with the diagnostic tool slide returning a personalised CharacterX read on each attendee's actual upcoming brief. The cumulative engagement model means later attendees see the running tally of which failure modes have been most common across all submitted briefs, building shared diagnostic experience over time.</p></div></section>

      <section className="py-16 lg:py-20"><div className="max-w-4xl mx-auto px-6 lg:px-8"><h2 className="text-3xl font-bold text-foreground mb-6">Register for the workshop</h2><div className="space-y-6 text-lg text-muted-foreground mb-8"><p>The workshop is free to attend. Register through the Flashbuzz workshop platform and you'll get immediate access — every attendee runs through the workshop independently, on their own schedule, with Norman guiding them through. You'll receive your brief diagnostic immediately and a follow-up email at day five offering a free written CharacterX brief review on your actual upcoming project, delivered within five working days, with no obligation to commission anything.</p><p>The brief review is genuinely useful as an independent strategic asset. It tells you what's wrong with the brief before you send it to a supplier. Whether you commission the resulting work with Flashbuzz, with another supplier, or in-house, the diagnostic does the same job: makes sure the next video doesn't underperform when the stakes are highest.</p></div><a href={registrationUrl} target="_blank" rel="noopener noreferrer" className="plausible-event-name=Video+Workshop+Register+Click" data-testid="video-workshop-register-footer"><Button size="lg">Register for the workshop<ArrowRight className="w-4 h-4 ml-2" /></Button></a></div></section>
    </div>
  );
}
